;; -*- mode: eask; lexical-binding: t -*-

(package "fuz-bin"
         "1.5.0"
         "Fast and precise fuzzy scoring/matching utils")

(website-url "https://github.com/jcs-elpa/fuz-bin")
(keywords "lisp")

(package-file "fuz-bin.el")

(script "test" "echo \"Error: no test specified\" && exit 1")

(source "melpa")

(depends-on "emacs" "26.1")

(setq network-security-level 'low)  ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
